# Generated by Django 3.2.3 on 2021-11-18 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('fee', models.IntegerField()),
                ('city', models.CharField(max_length=64)),
                ('exp', models.IntegerField()),
                ('lang', models.CharField(max_length=250)),
                ('spl', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='patappointment',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=50)),
                ('page', models.IntegerField()),
                ('paadhar', models.CharField(max_length=20)),
                ('pphone', models.PositiveBigIntegerField()),
                ('Date', models.DateField(max_length=50)),
                ('Time', models.TimeField(max_length=50)),
                ('psymptoms', models.CharField(max_length=640)),
                ('duname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duname', to='docchat.doctor')),
                ('uuname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uuname', to='docchat.user')),
            ],
        ),
    ]
