# Generated by Django 3.2.9 on 2021-12-06 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docchat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardname', models.CharField(max_length=120)),
                ('cardno', models.CharField(max_length=20)),
                ('bookid', models.PositiveBigIntegerField()),
                ('docuname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docuname', to='docchat.doctor')),
                ('patuname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patuname', to='docchat.user')),
            ],
        ),
    ]
