# Generated by Django 3.2.3 on 2021-11-11 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docchat', '0005_appointment_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='gp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.IntegerField()),
                ('city', models.CharField(max_length=64)),
                ('exp', models.IntegerField()),
                ('lang', models.CharField(max_length=250)),
                ('fn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fn', to='docchat.doctor')),
                ('iddoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iddoc', to='docchat.doctor')),
                ('ln', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ln', to='docchat.doctor')),
            ],
        ),
    ]
