# Generated by Django 3.2.3 on 2021-11-11 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docchat', '0006_gp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gp',
            name='fn',
        ),
        migrations.RemoveField(
            model_name='gp',
            name='ln',
        ),
    ]
