# Generated by Django 3.2.3 on 2021-11-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docchat', '0007_auto_20211111_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='city',
            field=models.CharField(default='ghj', max_length=64),
        ),
        migrations.AddField(
            model_name='doctor',
            name='exp',
            field=models.IntegerField(default='5'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='fee',
            field=models.IntegerField(default='5'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='lang',
            field=models.CharField(default='ri', max_length=250),
        ),
        migrations.DeleteModel(
            name='gp',
        ),
    ]
