# Generated by Django 3.2.3 on 2021-11-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docchat', '0008_auto_20211112_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='city',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='exp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='fee',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='lang',
            field=models.CharField(max_length=250),
        ),
    ]
