# Generated by Django 3.2.3 on 2021-11-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docchat', '0009_auto_20211112_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='spl',
            field=models.CharField(default='gp', max_length=4),
        ),
    ]
