# Generated by Django 3.2.3 on 2021-11-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docchat', '0011_alter_doctor_spl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='current_date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='current_time',
            new_name='Time',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
