# Generated by Django 3.2.3 on 2021-11-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docchat', '0012_auto_20211116_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lateappointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(max_length=50)),
                ('Time', models.TimeField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='appointment',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
